{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "Running the tests with Python 3.5.3, this traceback is dumped to the console:\r\n\r\n```\r\n$ nosetests3\r\n...................................................\r\n----------------------------------------------------------------------\r\nRan 51 tests in 1.613s\r\n\r\nOK\r\nException ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.5/asyncio/base_events.py\", line 511, in __del__\r\n  File \"/usr/lib/python3.5/asyncio/unix_events.py\", line 65, in close\r\n  File \"/usr/lib/python3.5/asyncio/unix_events.py\", line 146, in remove_signal_handler\r\n  File \"/usr/lib/python3.5/signal.py\", line 47, in signal\r\nTypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object\r\n```\r\n\r\nThis appears to be due to nothing explicitly `close()`ing the asyncio event loop.  There's discussion about this in Python issue [23548](https://bugs.python.org/issue23548).  As Guido [mentions](https://bugs.python.org/issue23548#msg236894), the automatic tear down of resources is only partially ordered, so we can't rely on that to properly clean up.\r\n\r\nEnabling asyncio's [suggested debugging](https://docs.python.org/3/library/asyncio-dev.html#asyncio-debug-mode) knobs also indicates that we're not closing all of the subprocess transport handles (likely similar for the other transports, too):\r\n\r\n```\r\n/usr/lib/python3.5/asyncio/base_subprocess.py:130: ResourceWarning: unclosed transport <_UnixSubprocessTransport pid=4782 running stdin=<_UnixWritePipeTransport fd=8 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=9 polling> stderr=<_UnixReadPipeTransport fd=11 polling>>\r\nsys:1: ResourceWarning: unclosed file <_io.FileIO name=9 mode='rb' closefd=True>\r\nsys:1: ResourceWarning: unclosed file <_io.FileIO name=11 mode='rb' closefd=True>\r\n/usr/lib/python3.5/asyncio/base_events.py:509: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=True>\r\nException ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=True>>\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.5/asyncio/base_events.py\", line 511, in __del__\r\n  File \"/usr/lib/python3.5/asyncio/unix_events.py\", line 65, in close\r\n  File \"/usr/lib/python3.5/asyncio/unix_events.py\", line 146, in remove_signal_handler\r\n  File \"/usr/lib/python3.5/signal.py\", line 47, in signal\r\nTypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object\r\nsys:1: ResourceWarning: unclosed file <_io.FileIO name=8 mode='wb' closefd=True>\r\n/usr/lib/python3.5/asyncio/unix_events.py:422: ResourceWarning: unclosed transport <_UnixReadPipeTransport closing fd=9 open>\r\n/usr/lib/python3.5/asyncio/unix_events.py:422: ResourceWarning: unclosed transport <_UnixReadPipeTransport closing fd=11 open>\r\n/usr/lib/python3.5/asyncio/unix_events.py:622: ResourceWarning: unclosed transport <_UnixWritePipeTransport closing fd=8 open>\r\n```\r\n\r\n---\r\nDiff to enable debugging knobs:\r\n\r\n```diff\r\ndiff --git a/neovim/msgpack_rpc/event_loop/asyncio.py b/neovim/msgpack_rpc/event_loop/asyncio.py\r\nindex b2ea77b..6e0edca 100644\r\n--- a/neovim/msgpack_rpc/event_loop/asyncio.py\r\n+++ b/neovim/msgpack_rpc/event_loop/asyncio.py\r\n@@ -23,6 +23,8 @@ except (ImportError, SyntaxError):\r\n \r\n from .base import BaseEventLoop\r\n \r\n+import warnings\r\n+warnings.simplefilter('default')\r\n \r\n loop_cls = asyncio.SelectorEventLoop\r\n if os.name == 'nt':\r\n@@ -72,6 +74,7 @@ class AsyncioEventLoop(BaseEventLoop, asyncio.Protocol,\r\n \r\n     def _init(self):\r\n         self._loop = loop_cls()\r\n+        self._loop.set_debug(True)\r\n         self._queued_data = deque()\r\n         self._fact = lambda: self\r\n \r\n```\r\n\r\nCc @mhinz",
    "closed_at": null,
    "closed_by": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/264/comments",
    "created_at": "2017-08-01T18:14:17Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/264/events",
    "html_url": "https://github.com/neovim/pynvim/issues/264",
    "id": 247155942,
    "issue_dependencies_summary": {
        "blocked_by": 0,
        "blocking": 0,
        "total_blocked_by": 0,
        "total_blocking": 0
    },
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/264/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUyNDcxNTU5NDI=",
    "number": 264,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 2,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 2,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/264/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/264/timeline",
    "title": "Event loop needs to have deterministic release of resources",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-09-22T19:33:13Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/264",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/112971?v=4",
        "events_url": "https://api.github.com/users/jamessan/events{/privacy}",
        "followers_url": "https://api.github.com/users/jamessan/followers",
        "following_url": "https://api.github.com/users/jamessan/following{/other_user}",
        "gists_url": "https://api.github.com/users/jamessan/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jamessan",
        "id": 112971,
        "login": "jamessan",
        "node_id": "MDQ6VXNlcjExMjk3MQ==",
        "organizations_url": "https://api.github.com/users/jamessan/orgs",
        "received_events_url": "https://api.github.com/users/jamessan/received_events",
        "repos_url": "https://api.github.com/users/jamessan/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jamessan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jamessan/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jamessan",
        "user_view_type": "public"
    }
}