{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Hello. I came from this issue: https://github.com/numirias/semshi/issues/11\r\n\r\nSummary: neovim prints this upon startup:\r\n```\r\nError detected while processing function remote#define#request:\r\nline    2:\r\nno request handler registered for \"/home/bz/rc.arch/bz/.vim/plugged/semshi/rplugin/python3/semshi:autocmd:BufEnter:*.py\"\r\n```\r\nIt only surfaced when I started using semshi. However, it does not look like it's a bug in the plugin, but rather in neovim/neovim-client. The author of the plugin could also reproduce the issue with the following configuration (see this comment https://github.com/numirias/semshi/issues/11#issuecomment-397452519):\r\n```vim\r\ncall plug#begin('~/.vim/plugged')\r\nPlug 'numirias/semshi'\r\nPlug 'autozimu/LanguageClient-neovim'\r\nPlug 'brooth/far.vim'\r\ncall plug#end()\r\n```\r\nThe following plugin can also help reproduce the issue:\r\n```python\r\nimport neovim\r\n\r\n@neovim.plugin\r\nclass Plugin:\r\n\r\n    def __init__(self, vim):\r\n        self._vim = vim\r\n\r\n    @neovim.autocmd('BufEnter', pattern='*', sync=True)\r\n    def foo(self):\r\n        self._vim.out_write('hey\\n')\r\n```\r\n\r\nneovim 0.3.0\r\nneovim-client 0.2.6",
    "closed_at": null,
    "closed_by": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "UpdateRemotePlugins is already executed?",
            "created_at": "2018-06-19T23:35:06Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-398578098",
            "id": 398578098,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5ODU3ODA5OA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/398578098/reactions"
            },
            "updated_at": "2018-06-19T23:35:06Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/398578098",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/41495?v=4",
                "events_url": "https://api.github.com/users/Shougo/events{/privacy}",
                "followers_url": "https://api.github.com/users/Shougo/followers",
                "following_url": "https://api.github.com/users/Shougo/following{/other_user}",
                "gists_url": "https://api.github.com/users/Shougo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Shougo",
                "id": 41495,
                "login": "Shougo",
                "node_id": "MDQ6VXNlcjQxNDk1",
                "organizations_url": "https://api.github.com/users/Shougo/orgs",
                "received_events_url": "https://api.github.com/users/Shougo/received_events",
                "repos_url": "https://api.github.com/users/Shougo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Shougo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Shougo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Shougo",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "@Shougo Yep. Installation of Python plugins (and registering their handlers) otherwise works fine.\r\n\r\nYou should be able to reproduce the bug with a minimal config using only these three plugins:\r\n\r\n```viml\r\ncall plug#begin('~/.vim/plugged')\r\nPlug 'numirias/semshi'\r\nPlug 'autozimu/LanguageClient-neovim'\r\nPlug 'brooth/far.vim'\r\ncall plug#end()\r\n```\r\n\r\nNote that they all are Python-powered and if you remove any single one of them the error disappears. But even if you replace one of them with the dummy plugin stub from above, the error will reappear. (While trying, obviously run `:UpdateRemotePlugins` each time.)\r\n\r\nWould love to see someone else repro it.",
            "created_at": "2018-06-20T00:13:01Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-398584274",
            "id": 398584274,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5ODU4NDI3NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/398584274/reactions"
            },
            "updated_at": "2018-06-20T00:13:28Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/398584274",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/29267777?v=4",
                "events_url": "https://api.github.com/users/numirias/events{/privacy}",
                "followers_url": "https://api.github.com/users/numirias/followers",
                "following_url": "https://api.github.com/users/numirias/following{/other_user}",
                "gists_url": "https://api.github.com/users/numirias/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/numirias",
                "id": 29267777,
                "login": "numirias",
                "node_id": "MDQ6VXNlcjI5MjY3Nzc3",
                "organizations_url": "https://api.github.com/users/numirias/orgs",
                "received_events_url": "https://api.github.com/users/numirias/received_events",
                "repos_url": "https://api.github.com/users/numirias/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/numirias/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/numirias/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/numirias",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I have tested it, but I cannot reproduce the problem.",
            "created_at": "2018-06-21T00:01:30Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-398934332",
            "id": 398934332,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5ODkzNDMzMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/398934332/reactions"
            },
            "updated_at": "2018-06-21T00:01:30Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/398934332",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/41495?v=4",
                "events_url": "https://api.github.com/users/Shougo/events{/privacy}",
                "followers_url": "https://api.github.com/users/Shougo/followers",
                "following_url": "https://api.github.com/users/Shougo/following{/other_user}",
                "gists_url": "https://api.github.com/users/Shougo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Shougo",
                "id": 41495,
                "login": "Shougo",
                "node_id": "MDQ6VXNlcjQxNDk1",
                "organizations_url": "https://api.github.com/users/Shougo/orgs",
                "received_events_url": "https://api.github.com/users/Shougo/received_events",
                "repos_url": "https://api.github.com/users/Shougo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Shougo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Shougo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Shougo",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "If it's a race condition, could you try with more plugins, e.g.:\r\n```vim\r\ncall plug#begin('~/.vim/plugged')\r\n\r\nPlug 'numirias/semshi'\r\n\r\nPlug 'autozimu/LanguageClient-neovim'\r\nPlug 'brooth/far.vim'\r\nPlug 'raghur/vim-ghost', {'do': ':GhostInstall'}\r\nPlug 'arakashic/chromatica.nvim'\r\nPlug 'Shougo/deoplete.nvim'\r\n\r\ncall plug#end()\r\n```",
            "created_at": "2018-06-21T06:29:31Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-398990970",
            "id": 398990970,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5ODk5MDk3MA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/398990970/reactions"
            },
            "updated_at": "2018-06-21T06:29:31Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/398990970",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/340676?v=4",
                "events_url": "https://api.github.com/users/balta2ar/events{/privacy}",
                "followers_url": "https://api.github.com/users/balta2ar/followers",
                "following_url": "https://api.github.com/users/balta2ar/following{/other_user}",
                "gists_url": "https://api.github.com/users/balta2ar/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/balta2ar",
                "id": 340676,
                "login": "balta2ar",
                "node_id": "MDQ6VXNlcjM0MDY3Ng==",
                "organizations_url": "https://api.github.com/users/balta2ar/orgs",
                "received_events_url": "https://api.github.com/users/balta2ar/received_events",
                "repos_url": "https://api.github.com/users/balta2ar/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/balta2ar/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/balta2ar/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/balta2ar",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "Confirm that I can reproduce the problem with the minimal config above.\r\nNeovim: 0.3.1, python-neovim: 0.2.6, macOS 10.14.",
            "created_at": "2018-10-28T15:50:24Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-433717188",
            "id": 433717188,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzMzcxNzE4OA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/433717188/reactions"
            },
            "updated_at": "2018-10-28T15:50:24Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/433717188",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/12573521?v=4",
                "events_url": "https://api.github.com/users/lkhphuc/events{/privacy}",
                "followers_url": "https://api.github.com/users/lkhphuc/followers",
                "following_url": "https://api.github.com/users/lkhphuc/following{/other_user}",
                "gists_url": "https://api.github.com/users/lkhphuc/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/lkhphuc",
                "id": 12573521,
                "login": "lkhphuc",
                "node_id": "MDQ6VXNlcjEyNTczNTIx",
                "organizations_url": "https://api.github.com/users/lkhphuc/orgs",
                "received_events_url": "https://api.github.com/users/lkhphuc/received_events",
                "repos_url": "https://api.github.com/users/lkhphuc/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/lkhphuc/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lkhphuc/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/lkhphuc",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "Many shaky race conditions have been fixed in Neovim since, so chances are this bug might be gone. \r\n\r\n@balta2ar @lkhphuc Can you still reproduce? Otherwise, I think this can be closed.",
            "created_at": "2019-03-27T15:10:19Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-477200787",
            "id": 477200787,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NzIwMDc4Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/477200787/reactions"
            },
            "updated_at": "2019-03-27T15:10:44Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/477200787",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/29267777?v=4",
                "events_url": "https://api.github.com/users/numirias/events{/privacy}",
                "followers_url": "https://api.github.com/users/numirias/followers",
                "following_url": "https://api.github.com/users/numirias/following{/other_user}",
                "gists_url": "https://api.github.com/users/numirias/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/numirias",
                "id": 29267777,
                "login": "numirias",
                "node_id": "MDQ6VXNlcjI5MjY3Nzc3",
                "organizations_url": "https://api.github.com/users/numirias/orgs",
                "received_events_url": "https://api.github.com/users/numirias/received_events",
                "repos_url": "https://api.github.com/users/numirias/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/numirias/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/numirias/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/numirias",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "@numirias I'm using neovim 0.3.3, pynvim 0.3.2 and I can consistently reproduce very similar error message with the following plugin:\r\n\r\n```python\r\nimport pynvim\r\n\r\n\r\n@pynvim.plugin\r\nclass Main(object):\r\n    def __init__(self, nvim):\r\n        self.nvim = nvim\r\n\r\n    @pynvim.autocmd('BufWritePost', pattern='*', eval='expand(\"<afile>:p\")')\r\n    def update_tags_for_file(self, filename):\r\n        self.update_screen()\r\n\r\n    @property\r\n    def extrawidth(self):\r\n        numberwidth = self.nvim.eval(\r\n            '((&number||&relativenumber) ? &numberwidth : 0) + &foldcolumn')\r\n        self.nvim.command(\r\n            'redir =>a |exe \"sil sign place buffer=\".bufnr(\\'\\')|redir end')\r\n        signlist = self.nvim.command_output('echo a').split('\\n')\r\n        signwidth = 2 if len(signlist) > 2 else 0\r\n        separator = 1\r\n\r\n        result = numberwidth + signwidth\r\n        result += separator if numberwidth > 0 else 0\r\n        result += separator if signwidth > 0 else 0\r\n        return result\r\n\r\n    def pad_message(self, message, index):\r\n        winwidth = self.nvim.eval('winwidth(\"%\")')\r\n        linewidth = self.nvim.eval(\r\n            'strdisplaywidth(getline(%s))' % (index + 1)) + self.extrawidth\r\n        sumwidth = len(message)\r\n        padwidth = max(0, winwidth - linewidth - sumwidth)\r\n        padding = ' ' * padwidth\r\n        padded_message = padding + message\r\n\r\n        return padded_message\r\n\r\n    def update_screen(self):\r\n        highlight_group = 'LineNr'\r\n\r\n        line_start = self.nvim.eval('line(\"w0\")') - 1\r\n        line_end = self.nvim.eval('line(\"w$\")')\r\n        lines = self.nvim.current.buffer[line_start:line_end]\r\n\r\n        api = self.nvim.current.buffer.api\r\n        api.clear_namespace(-1, 0, -1)\r\n        for line, index in zip(lines, range(line_start, line_end)):\r\n            text = 'Mocked'\r\n            message = self.pad_message(text, index)\r\n            api.set_virtual_text(0, index, [[message, highlight_group]], {})\r\n```\r\nThe error I see when I do `:w` is this:\r\n```\r\nno notification handler registered for \"/home/username/rc.arch/bz/.vim/plugged/timesheet.nvim/rplugin/python3/timesheet.py:autocmd:BufWritePost:*\"\r\n```\r\nIf I remove the two lines below, the error disappears:\r\n```\r\n        numberwidth = self.nvim.eval(\r\n            '((&number||&relativenumber) ? &numberwidth : 0) + &foldcolumn')\r\n        self.nvim.command(\r\n            'redir =>a |exe \"sil sign place buffer=\".bufnr(\\'\\')|redir end')\r\n```\r\nMaybe it's a problem with my code, not neovim or pynvim, could you tell it from the code?",
            "created_at": "2019-03-27T16:57:29Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-477253559",
            "id": 477253559,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NzI1MzU1OQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/477253559/reactions"
            },
            "updated_at": "2019-03-27T16:57:29Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/477253559",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/340676?v=4",
                "events_url": "https://api.github.com/users/balta2ar/events{/privacy}",
                "followers_url": "https://api.github.com/users/balta2ar/followers",
                "following_url": "https://api.github.com/users/balta2ar/following{/other_user}",
                "gists_url": "https://api.github.com/users/balta2ar/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/balta2ar",
                "id": 340676,
                "login": "balta2ar",
                "node_id": "MDQ6VXNlcjM0MDY3Ng==",
                "organizations_url": "https://api.github.com/users/balta2ar/orgs",
                "received_events_url": "https://api.github.com/users/balta2ar/received_events",
                "repos_url": "https://api.github.com/users/balta2ar/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/balta2ar/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/balta2ar/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/balta2ar",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "    no notification handler registered for \"/home/username/rc.arch/bz/.vim/plugged/timesheet.nvim/rplugin/python3/timesheet.py:autocmd:BufWritePost:*\"\r\n\r\n\r\nThat definitely looks wrong. The \"method name\" `\"/home/username/.../timesheet.py:autocmd:BufWritePost:*` is nonsense. Somewhere that's being passed as a method name. Most likely a bug in `runtime/autoload/remote/define.vim` .",
            "created_at": "2019-03-27T21:14:34Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-477350279",
            "id": 477350279,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NzM1MDI3OQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/477350279/reactions"
            },
            "updated_at": "2019-03-27T21:14:34Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/477350279",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I'm having this exact same thing happen to me while attempting to write a plugin...\r\n\r\nweird thing is that after the first attempt failing, the rest succeed.",
            "created_at": "2019-04-11T16:44:15Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-482193920",
            "id": 482193920,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ4MjE5MzkyMA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 4,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 4,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/482193920/reactions"
            },
            "updated_at": "2019-04-11T16:44:15Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/482193920",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/4466899?v=4",
                "events_url": "https://api.github.com/users/tjdevries/events{/privacy}",
                "followers_url": "https://api.github.com/users/tjdevries/followers",
                "following_url": "https://api.github.com/users/tjdevries/following{/other_user}",
                "gists_url": "https://api.github.com/users/tjdevries/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tjdevries",
                "id": 4466899,
                "login": "tjdevries",
                "node_id": "MDQ6VXNlcjQ0NjY4OTk=",
                "organizations_url": "https://api.github.com/users/tjdevries/orgs",
                "received_events_url": "https://api.github.com/users/tjdevries/received_events",
                "repos_url": "https://api.github.com/users/tjdevries/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tjdevries/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tjdevries/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tjdevries",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I just had the exact same issue happening to me with only \r\n```\r\nPlug 'autozimu/LanguageClient-neovim'\r\n```\r\nthough. Can't seem to figure it out though, and the magic `UpdateRemotePlugins` does something for me, but does not solve my problem (even after repeated execution).",
            "created_at": "2019-10-13T07:42:43Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-541395382",
            "id": 541395382,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDU0MTM5NTM4Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/541395382/reactions"
            },
            "updated_at": "2019-10-13T07:42:43Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/541395382",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/9039899?v=4",
                "events_url": "https://api.github.com/users/fkarg/events{/privacy}",
                "followers_url": "https://api.github.com/users/fkarg/followers",
                "following_url": "https://api.github.com/users/fkarg/following{/other_user}",
                "gists_url": "https://api.github.com/users/fkarg/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/fkarg",
                "id": 9039899,
                "login": "fkarg",
                "node_id": "MDQ6VXNlcjkwMzk4OTk=",
                "organizations_url": "https://api.github.com/users/fkarg/orgs",
                "received_events_url": "https://api.github.com/users/fkarg/received_events",
                "repos_url": "https://api.github.com/users/fkarg/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/fkarg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fkarg/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/fkarg",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I can reproduce this as well, with this fairly minimal plugin:\r\n\r\n```py\r\n\"\"\"An RPC client for Neovim.\"\"\"\r\nimport pynvim\r\nimport pypresence\r\nimport asyncio\r\nfrom datetime import datetime\r\n\r\n\r\n@pynvim.plugin\r\nclass Neocord:\r\n    \"\"\"The core class for Neocord.\"\"\"\r\n\r\n    def __init__(self, nvim):\r\n        \"\"\"Initialize the plugin.\"\"\"\r\n        self.nvim = nvim\r\n        self.client_id = self.nvim.vars.get(\"neocord_clientid\")\r\n        if self.client_id is None:\r\n            self.client_id = 655548219425554464\r\n        self.presence = pypresence.AioClient(\r\n            self.client_id,\r\n            loop=self.nvim.loop\r\n        )\r\n        self.presence.start()\r\n        self.enter_time = datetime.now()\r\n        self.pid = self.nvim.api.get_api_info()[0]\r\n\r\n    @pynvim.autocmd('BufEnter', pattern='*')\r\n    async def on_bufenter(self):\r\n        \"\"\"Run on opening a buffer.\"\"\"\r\n        current_buf = self.nvim.current.buffer\r\n        await self.presence.set_activity(\r\n                state=f\"Editing buffer {current_buf.name}\",\r\n                start=self.enter_time.timestamp(),\r\n                pid=self.pid\r\n            )\r\n\r\n    @pynvim.autocmd('VimEnter', pattern='*')\r\n    async def on_vimenter(self):\r\n        \"\"\"Run on opening a vim session.\"\"\"\r\n        current_buf = self.nvim.current.buffer\r\n        await self.presence.set_activity(\r\n                state=f\"Editing buffer {current_buf.name}\",\r\n                start=self.enter_time.timestamp(),\r\n                pid=self.pid\r\n            )\r\n```\r\nas well as this (super) minimal vimrc:\r\n```vim\r\nlet &runtimepath.=','.escape(expand('<sfile>:p:h'), '\\,')\r\n```",
            "created_at": "2019-12-15T15:57:21Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-565821947",
            "id": 565821947,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "MDEyOklzc3VlQ29tbWVudDU2NTgyMTk0Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/565821947/reactions"
            },
            "updated_at": "2019-12-15T15:57:21Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/565821947",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/44379526?v=4",
                "events_url": "https://api.github.com/users/DrBluefall/events{/privacy}",
                "followers_url": "https://api.github.com/users/DrBluefall/followers",
                "following_url": "https://api.github.com/users/DrBluefall/following{/other_user}",
                "gists_url": "https://api.github.com/users/DrBluefall/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/DrBluefall",
                "id": 44379526,
                "login": "DrBluefall",
                "node_id": "MDQ6VXNlcjQ0Mzc5NTI2",
                "organizations_url": "https://api.github.com/users/DrBluefall/orgs",
                "received_events_url": "https://api.github.com/users/DrBluefall/received_events",
                "repos_url": "https://api.github.com/users/DrBluefall/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/DrBluefall/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/DrBluefall/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/DrBluefall",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I had the issue with incorrect `g:python3_host_prog`. Try doing `:checkhealth` once",
            "created_at": "2021-07-24T07:32:59Z",
            "html_url": "https://github.com/neovim/pynvim/issues/341#issuecomment-886014345",
            "id": 886014345,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/341",
            "node_id": "IC_kwDOASpKTs40z4GJ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/886014345/reactions"
            },
            "updated_at": "2021-07-24T07:32:59Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/886014345",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/45873379?v=4",
                "events_url": "https://api.github.com/users/tejasvi/events{/privacy}",
                "followers_url": "https://api.github.com/users/tejasvi/followers",
                "following_url": "https://api.github.com/users/tejasvi/following{/other_user}",
                "gists_url": "https://api.github.com/users/tejasvi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tejasvi",
                "id": 45873379,
                "login": "tejasvi",
                "node_id": "MDQ6VXNlcjQ1ODczMzc5",
                "organizations_url": "https://api.github.com/users/tejasvi/orgs",
                "received_events_url": "https://api.github.com/users/tejasvi/received_events",
                "repos_url": "https://api.github.com/users/tejasvi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tejasvi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tejasvi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tejasvi",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 12,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/341/comments",
    "created_at": "2018-06-19T14:14:50Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/341/events",
    "html_url": "https://github.com/neovim/pynvim/issues/341",
    "id": 333691547,
    "issue_dependencies_summary": {
        "blocked_by": 0,
        "blocking": 0,
        "total_blocked_by": 0,
        "total_blocking": 0
    },
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/341/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzMzM2OTE1NDc=",
    "number": 341,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 2,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 2,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/341/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/341/timeline",
    "title": "no request handler registered for \"/home/me/dummy/rplugin/python3/dummy:autocmd:BufEnter:*\"",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-09-22T19:33:14Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/341",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/340676?v=4",
        "events_url": "https://api.github.com/users/balta2ar/events{/privacy}",
        "followers_url": "https://api.github.com/users/balta2ar/followers",
        "following_url": "https://api.github.com/users/balta2ar/following{/other_user}",
        "gists_url": "https://api.github.com/users/balta2ar/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/balta2ar",
        "id": 340676,
        "login": "balta2ar",
        "node_id": "MDQ6VXNlcjM0MDY3Ng==",
        "organizations_url": "https://api.github.com/users/balta2ar/orgs",
        "received_events_url": "https://api.github.com/users/balta2ar/received_events",
        "repos_url": "https://api.github.com/users/balta2ar/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/balta2ar/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/balta2ar/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/balta2ar",
        "user_view_type": "public"
    }
}