{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "## Problem\r\n\r\nI'm trying to use an `autocmd` via the [remote-plugin](https://pynvim.readthedocs.io/en/latest/plugin-decorators.html#pynvim.plugin.autocmd) documentation, and running into errors.\r\n\r\n```bash\r\n$ python -V\r\nPython 3.8.6\r\n$ pip -V\r\npip 19.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8) \r\n$ pip list installed | grep -i pynvim\r\npynvim          0.4.2 \r\n$ nvim --version\r\nNVIM v0.5.0-812-gd17e50879\r\nBuild type: RelWithDebInfo\r\nLuaJIT 2.1.0-beta3\r\nCompilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include\r\nCompiled by travis@travis-job-317a2489-aba5-414a-b9f3-9551746c326c\r\n```\r\n\r\n---\r\n\r\n## Setup\r\n\r\nLooking at the generated manifest file `/home/user/.local/share/nvim/rplugin.vim`:\r\n\r\n```vim\r\n\" perl plugins\r\n\r\n\r\n\" node plugins\r\n\r\n\r\n\" python3 plugins\r\ncall remote#host#RegisterPlugin('python3', '/home/user/.config/nvim/rplugin/python3/pluginctl.py', [\r\n      \\ {'sync': v:true, 'name': 'Plugin', 'type': 'command', 'opts': {'nargs': '+'}},\r\n      \\ {'sync': v:false, 'name': 'PluginClean', 'type': 'command', 'opts': {'nargs': '0'}},\r\n      \\ {'sync': v:false, 'name': 'PluginInstall', 'type': 'command', 'opts': {'bang': '', 'nargs': '0'}},\r\n     \\ ])\r\ncall remote#host#RegisterPlugin('python3', '/home/user/.config/nvim/rplugin/python3/terminalctl.py', [\r\n      \\ {'sync': v:true, 'name': 'TabNew', 'type': 'autocmd', 'opts': {'pattern': '*'}},\r\n      \\ {'sync': v:true, 'name': 'TerminalToggle', 'type': 'command', 'opts': {'nargs': '0'}},\r\n     \\ ])\r\n\r\n\r\n\" ruby plugins\r\n\r\n\r\n\" python plugins\r\n```\r\n\r\nand then loading up a `~/.config/nvim/init.vim` which only contains:\r\n\r\n```vim\r\nruntime! plugin/rplugin.vim | silent! UpdateRemotePlugins\r\n```\r\n\r\nand the relevant parts of `/home/user/.config/nvim/rplugin/python3/terminalctl.py`:\r\n\r\n```python\r\nfrom pynvim import (\r\n    autocmd,\r\n    command,\r\n    plugin,\r\n)\r\n\r\n\r\n@plugin\r\nclass TerminalCtl(object):\r\n    def __init__(self, nvim):\r\n        self.nvim = nvim\r\n\r\n    @command('TerminalToggle', nargs='0', sync=True)\r\n    def _terminal_toggle(\r\n            self,\r\n            args\r\n        ):\r\n       pass\r\n\r\n    @autocmd('TabNew', pattern='*', sync=True)\r\n    def _tab_id(\r\n            self,\r\n        ):\r\n        pass\r\n```\r\n\r\nwhich is a pretty simplistic example. We can also see that _Neovim_ recognizes the `autocmd` internally:\r\n\r\n```vim\r\n:autocmd TabNew                                                                                   \r\n--- Autocommands ---\r\nRPC_DEFINE_AUTOCMD_GROUP_1  TabNew\r\n    *         call remote#define#AutocmdBootstrap(\"python3\", \"/home/user/.config/nvim/rplugin/python3/terminalctl.py:autocmd:TabNew:*\", v:true, \"Tab\r\nNew\", {'group': 'RPC_DEFINE_AUTOCMD_GROUP_1', 'pattern': '*'}, \"\\\"doau RPC_DEFINE_AUTOCMD_GROUP_1 TabNew \\\".fnameescape(expand(\\\"<amatch>\\\"))\")\r\n```\r\n\r\n**Note that the commands work just fine, it is the autocmds that fail.**\r\n\r\n## Traceback\r\n\r\nWhen I try to run `:tabnew`, triggering the `autocmd`, I get the following stack trace:\r\n\r\n```\r\nError detected while processing function remote#define#request:                                                                                  \r\nline    2:\r\nerror caught in request handler '/home/user/.config/nvim/rplugin/python3/terminalctl.py:autocmd:TabNew:* []'\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.8/site-packages/pynvim/plugin/host.py\", line 129, in _on_request\r\n    rv = handler(*args)\r\n  File \"/usr/local/lib/python3.8/site-packages/pynvim/plugin/host.py\", line 95, in _wrap_delayed_function\r\n    self._request_handlers[name](*args)\r\nKeyError: '/home/user/.config/nvim/rplugin/python3/terminalctl.py:autocmd:TabNew:*'\r\nError invoking '/home/user/.config/nvim/rplugin/python3/terminalctl.py:autocmd:TabNew:*' on channel 4 (python3-rplugin-host):\r\nKeyError('/home/user/.config/nvim/rplugin/python3/terminalctl.py:autocmd:TabNew:*')\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py\", line 200, in handler\r\n    rv = self._request_cb(name, args)\r\n  File \"/usr/local/lib/python3.8/site-packages/pynvim/api/nvim.py\", line 210, in filter_request_cb\r\n    result = request_cb(name, args)\r\n  File \"/usr/local/lib/python3.8/site-packages/pynvim/plugin/host.py\", line 129, in _on_request\r\n    rv = handler(*args)\r\n  File \"/usr/local/lib/python3.8/site-packages/pynvim/plugin/host.py\", line 95, in _wrap_delayed_function\r\n    self._request_handlers[name](*args)\r\n```\r\n\r\nso we are getting a `KeyError` for `/home/user/.config/nvim/rplugin/python3/terminalctl.py:autocmd:TabNew:*` in the file `/usr/local/lib/python3.8/site-packages/pynvim/plugin/host.py` on line `95`. If I open this file, I can do something like:\r\n\r\n```python\r\n        if sync:\r\n            with open('/home/user/foo', 'w') as fd:\r\n                fd.write(str(self._request_handlers))\r\n\r\n            self._request_handlers[name](*args)\r\n        else:\r\n            self._notification_handlers[name](*args)\r\n```\r\n\r\nwhich will then write the string to `/home/user/foo`, opening it:\r\n\r\n```python\r\n{\r\n    'poll': <function Host.__init__.<locals>.<lambda> at 0x7fad25255430>,\r\n    'specs': <bound method Host._on_specs_request of <pynvim.plugin.host.Host object at 0x7fad25252e20>>,\r\n    'shutdown': <bound method Host.shutdown of <pynvim.plugin.host.Host object at 0x7fad25252e20>>,\r\n    '/home/user/.config/nvim/rplugin/python3/pluginctl.py:command:Plugin': functools.partial(<bound method Host._wrap_function of <pynvim.plugin.host.Host object at 0x7fad25252e20>>, <bound method PluginCtl._plugin_add of <pluginctl.PluginCtl object at 0x7fad24d123a0>>, True, True, None, '/home/user/.config/nvim/rplugin/python3/pluginctl.py:command:Plugin'),\r\n    '/home/user/.config/nvim/rplugin/python3/terminalctl.py:command:TerminalToggle': functools.partial(<bound method Host._wrap_function of <pynvim.plugin.host.Host object at 0x7fad25252e20>>, <bound method TerminalCtl._terminal_toggle of <terminalctl.TerminalCtl object at 0x7fad24d12940>>, True, True, None, '/home/user/.config/nvim/rplugin/python3/terminalctl.py:command:TerminalToggle')\r\n}\r\n```\r\n\r\nso we can see that the `autocmd` just isn't stored. I can change the decorator to specify `sync=False`, and see the same thing, but a different flavor:\r\n\r\n```python\r\nError detected while processing function remote#define#request:                                                                                   \r\nline    2:\r\nError invoking '/home/user/.config/nvim/rplugin/python3/terminalctl.py:autocmd:TabNew:*' on channel 4 (python3-rplugin-host):\r\nno request handler registered for \"/home/user/.config/nvim/rplugin/python3/terminalctl.py:autocmd:TabNew:*\"\r\n```\r\n\r\n## Fin\r\n\r\nSo what am I missing here?",
    "closed_at": null,
    "closed_by": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/467/comments",
    "created_at": "2020-11-17T02:59:26Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/467/events",
    "html_url": "https://github.com/neovim/pynvim/issues/467",
    "id": 744366360,
    "issue_dependencies_summary": {
        "blocked_by": 0,
        "blocking": 0,
        "total_blocked_by": 0,
        "total_blocking": 0
    },
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/467/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU3NDQzNjYzNjA=",
    "number": 467,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/467/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/467/timeline",
    "title": "autocmd KeyError",
    "type": {
        "color": "red",
        "created_at": "2024-01-25T10:10:19Z",
        "description": "An unexpected problem or behavior",
        "id": 597163,
        "is_enabled": true,
        "name": "Bug",
        "node_id": "IT_kwDOAGK_Pc4ACRyr",
        "updated_at": "2024-07-26T10:12:30Z"
    },
    "updated_at": "2025-09-22T19:35:56Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/467",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/31262046?v=4",
        "events_url": "https://api.github.com/users/levouh/events{/privacy}",
        "followers_url": "https://api.github.com/users/levouh/followers",
        "following_url": "https://api.github.com/users/levouh/following{/other_user}",
        "gists_url": "https://api.github.com/users/levouh/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/levouh",
        "id": 31262046,
        "login": "levouh",
        "node_id": "MDQ6VXNlcjMxMjYyMDQ2",
        "organizations_url": "https://api.github.com/users/levouh/orgs",
        "received_events_url": "https://api.github.com/users/levouh/received_events",
        "repos_url": "https://api.github.com/users/levouh/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/levouh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/levouh/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/levouh",
        "user_view_type": "public"
    }
}