{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "\r\nCurl is installed in my windows system. I could individually run `curl https://pypi.python.org/pypi/pynvim/json` and no error. However, when i run `neovim :checkhealth`, facing this error in the report. \r\n\r\n\r\n`: checkhealth` output:\r\n\r\n```\r\nPython 3 provider (optional) ~\r\n- pyenv: Path: C:\\Users\\<username>\\.pyenv\\pyenv-win\\bin\\pyenv.BAT\r\n- pyenv: Root: C:\\Users\\<username>\\.pyenv\\pyenv-win\\\r\n- Using: g:python3_host_prog = \"C:/Python312/python.exe\"\r\n- Executable: C:\\Python312\\python.exe\r\n- Python version: 3.12.0\r\n- pynvim version: 0.5.0\r\n- WARNING Could not contact PyPI to get latest version.\r\n- ERROR HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 35\r\n```\r\n",
    "closed_at": "2023-12-23T08:31:22Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
        "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
        "followers_url": "https://api.github.com/users/wookayin/followers",
        "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
        "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/wookayin",
        "id": 1009873,
        "login": "wookayin",
        "node_id": "MDQ6VXNlcjEwMDk4NzM=",
        "organizations_url": "https://api.github.com/users/wookayin/orgs",
        "received_events_url": "https://api.github.com/users/wookayin/received_events",
        "repos_url": "https://api.github.com/users/wookayin/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/wookayin",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "- Does that happen always -- not a temporary problem?\r\n- What is your neovim version?\r\n- Can you try `!curl -sL https://pypi.python.org/pypi/pynvim/json` and does it print JSON data successfully?",
            "created_at": "2023-12-15T05:32:24Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1857303724",
            "id": 1857303724,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5utDSs",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1857303724/reactions"
            },
            "updated_at": "2023-12-15T05:32:24Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1857303724",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "\r\n1. Yes, the error occurs always\r\n2. NVIM v0.9.4\r\n3. Output of `:!curl -sL https://pypi.python.org/pypi/pynvim/json`\r\n```pwsh\r\ncurl: (3) URL rejected: Bad hostname\r\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\r\n                                 Dload  Upload   Total   Spent    Left  Speed\r\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r\ncurl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revoc\r\nation function was unable to check revocation for the certificate.\r\n\r\nshell returned 35\r\n```",
            "created_at": "2023-12-15T17:28:08Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1858232801",
            "id": 1858232801,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5uwmHh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1858232801/reactions"
            },
            "updated_at": "2025-02-14T12:23:30Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1858232801",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3577158?v=4",
                "events_url": "https://api.github.com/users/sudheer82/events{/privacy}",
                "followers_url": "https://api.github.com/users/sudheer82/followers",
                "following_url": "https://api.github.com/users/sudheer82/following{/other_user}",
                "gists_url": "https://api.github.com/users/sudheer82/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/sudheer82",
                "id": 3577158,
                "login": "sudheer82",
                "node_id": "MDQ6VXNlcjM1NzcxNTg=",
                "organizations_url": "https://api.github.com/users/sudheer82/orgs",
                "received_events_url": "https://api.github.com/users/sudheer82/received_events",
                "repos_url": "https://api.github.com/users/sudheer82/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/sudheer82/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sudheer82/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/sudheer82",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "`-sL`, not `=sL`. Try `:!curl --verbose -fL https://pypi.python.org/pypi/pynvim/json` for debugging.\r\n\r\nFrom the output, there was an issue while validating the certificate. What's the output of `curl --version`?\r\n\r\nAnyway this does not seem relevant to pynvim.",
            "created_at": "2023-12-17T08:46:48Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1859075899",
            "id": 1859075899,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5uzz87",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1859075899/reactions"
            },
            "updated_at": "2023-12-17T08:47:17Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1859075899",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Closing as no response was received and this doesn't seem to be a problem of neovim/pynvim. Try to fix `curl` (certificate issues) in the command line (or run them within the neovim).",
            "created_at": "2023-12-23T08:31:22Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1868241613",
            "id": 1868241613,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5vWxrN",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1868241613/reactions"
            },
            "updated_at": "2023-12-23T08:31:22Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1868241613",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I have used `-sL` only. it was a typo in the comment",
            "created_at": "2023-12-30T05:00:38Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1872452974",
            "id": 1872452974,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5vm11u",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1872452974/reactions"
            },
            "updated_at": "2023-12-30T05:00:38Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1872452974",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3577158?v=4",
                "events_url": "https://api.github.com/users/sudheer82/events{/privacy}",
                "followers_url": "https://api.github.com/users/sudheer82/followers",
                "following_url": "https://api.github.com/users/sudheer82/following{/other_user}",
                "gists_url": "https://api.github.com/users/sudheer82/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/sudheer82",
                "id": 3577158,
                "login": "sudheer82",
                "node_id": "MDQ6VXNlcjM1NzcxNTg=",
                "organizations_url": "https://api.github.com/users/sudheer82/orgs",
                "received_events_url": "https://api.github.com/users/sudheer82/received_events",
                "repos_url": "https://api.github.com/users/sudheer82/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/sudheer82/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sudheer82/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/sudheer82",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Yes, let me know if the problem still persists.",
            "created_at": "2023-12-30T05:02:21Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1872453234",
            "id": 1872453234,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5vm15y",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1872453234/reactions"
            },
            "updated_at": "2023-12-30T05:02:21Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1872453234",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "I also encountered the same problem. I feel this may be a network configuration issue. I am using wsl, so in windows, I executed: netsh winsock reset, and the problem was solved after restarting my PC.",
            "created_at": "2024-01-09T03:35:59Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1882349441",
            "id": 1882349441,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5wMl-B",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1882349441/reactions"
            },
            "updated_at": "2024-01-09T03:35:59Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1882349441",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/82327624?v=4",
                "events_url": "https://api.github.com/users/ILOT-code/events{/privacy}",
                "followers_url": "https://api.github.com/users/ILOT-code/followers",
                "following_url": "https://api.github.com/users/ILOT-code/following{/other_user}",
                "gists_url": "https://api.github.com/users/ILOT-code/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ILOT-code",
                "id": 82327624,
                "login": "ILOT-code",
                "node_id": "MDQ6VXNlcjgyMzI3NjI0",
                "organizations_url": "https://api.github.com/users/ILOT-code/orgs",
                "received_events_url": "https://api.github.com/users/ILOT-code/received_events",
                "repos_url": "https://api.github.com/users/ILOT-code/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ILOT-code/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ILOT-code/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ILOT-code",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Sorry to hear that, but if you don't provide what exactly happened in curl's output there's nothing much to be helped with or improved. Not sure whether the network was really unavailable, or network/internet was fine but only the curl on WSL was buggy and stopped working.",
            "created_at": "2024-01-09T03:51:09Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1882371519",
            "id": 1882371519,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5wMrW_",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1882371519/reactions"
            },
            "updated_at": "2024-01-09T03:51:09Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1882371519",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "any fixes? i'm on arch and i have the excat same issue when im connect with my home network. When i turn on a vpn or connect through my mobile tethering everything goes fine",
            "created_at": "2024-10-18T17:33:01Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-2422937322",
            "id": 2422937322,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs6Qaxbq",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2422937322/reactions"
            },
            "updated_at": "2024-10-18T17:33:01Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2422937322",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/118215820?v=4",
                "events_url": "https://api.github.com/users/schlosserleo/events{/privacy}",
                "followers_url": "https://api.github.com/users/schlosserleo/followers",
                "following_url": "https://api.github.com/users/schlosserleo/following{/other_user}",
                "gists_url": "https://api.github.com/users/schlosserleo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/schlosserleo",
                "id": 118215820,
                "login": "schlosserleo",
                "node_id": "U_kgDOBwvUjA",
                "organizations_url": "https://api.github.com/users/schlosserleo/orgs",
                "received_events_url": "https://api.github.com/users/schlosserleo/received_events",
                "repos_url": "https://api.github.com/users/schlosserleo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/schlosserleo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/schlosserleo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/schlosserleo",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "Yes, it exists \n\n> Yes, let me know if the problem still persists.\n\n",
            "created_at": "2025-02-14T12:24:10Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-2659204421",
            "id": 2659204421,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs6egD1F",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2659204421/reactions"
            },
            "updated_at": "2025-02-14T12:24:10Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2659204421",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3577158?v=4",
                "events_url": "https://api.github.com/users/sudheer82/events{/privacy}",
                "followers_url": "https://api.github.com/users/sudheer82/followers",
                "following_url": "https://api.github.com/users/sudheer82/following{/other_user}",
                "gists_url": "https://api.github.com/users/sudheer82/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/sudheer82",
                "id": 3577158,
                "login": "sudheer82",
                "node_id": "MDQ6VXNlcjM1NzcxNTg=",
                "organizations_url": "https://api.github.com/users/sudheer82/orgs",
                "received_events_url": "https://api.github.com/users/sudheer82/received_events",
                "repos_url": "https://api.github.com/users/sudheer82/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/sudheer82/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sudheer82/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/sudheer82",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "always need exact version info",
            "created_at": "2025-02-14T12:37:40Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-2659232849",
            "id": 2659232849,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs6egKxR",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2659232849/reactions"
            },
            "updated_at": "2025-02-14T12:37:40Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2659232849",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "coming back to this, it seemed the problem was on my isp. when i refreshed my ipv6 multiple times on my router till i got a different ipv6 the issue was gone",
            "created_at": "2025-04-08T12:44:11Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-2786317611",
            "id": 2786317611,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs6mE9Ur",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2786317611/reactions"
            },
            "updated_at": "2025-04-08T12:44:11Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2786317611",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/118215820?v=4",
                "events_url": "https://api.github.com/users/schlosserleo/events{/privacy}",
                "followers_url": "https://api.github.com/users/schlosserleo/followers",
                "following_url": "https://api.github.com/users/schlosserleo/following{/other_user}",
                "gists_url": "https://api.github.com/users/schlosserleo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/schlosserleo",
                "id": 118215820,
                "login": "schlosserleo",
                "node_id": "U_kgDOBwvUjA",
                "organizations_url": "https://api.github.com/users/schlosserleo/orgs",
                "received_events_url": "https://api.github.com/users/schlosserleo/received_events",
                "repos_url": "https://api.github.com/users/schlosserleo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/schlosserleo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/schlosserleo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/schlosserleo",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 12,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/557/comments",
    "created_at": "2023-12-15T03:54:34Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/557/events",
    "html_url": "https://github.com/neovim/pynvim/issues/557",
    "id": 2042848214,
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/557/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs55w2PW",
    "number": 557,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/557/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "closed",
    "state_reason": "not_planned",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/557/timeline",
    "title": "checkhealth WARNING: Could not contact PyPI to get latest version",
    "type": null,
    "updated_at": "2025-04-08T12:44:12Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/557",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3577158?v=4",
        "events_url": "https://api.github.com/users/sudheer82/events{/privacy}",
        "followers_url": "https://api.github.com/users/sudheer82/followers",
        "following_url": "https://api.github.com/users/sudheer82/following{/other_user}",
        "gists_url": "https://api.github.com/users/sudheer82/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/sudheer82",
        "id": 3577158,
        "login": "sudheer82",
        "node_id": "MDQ6VXNlcjM1NzcxNTg=",
        "organizations_url": "https://api.github.com/users/sudheer82/orgs",
        "received_events_url": "https://api.github.com/users/sudheer82/received_events",
        "repos_url": "https://api.github.com/users/sudheer82/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/sudheer82/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sudheer82/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/sudheer82",
        "user_view_type": "public"
    }
}